nodejs/aws-infra/network.ts
=> Export route tables on Network

nodejs/aws-infra/examples/ec2/index.ts, nodejs/aws-infra/examples/fargate/index.ts, nodejs/aws-infra/experimental/autoscaling/autoscaling.ts, nodejs/aws-infra/experimental/clusterFileSystem.ts, nodejs/aws-infra/experimental/ec2/cidr.ts, nodejs/aws-infra/experimental/ec2/index.ts, nodejs/aws-infra/experimental/ec2/securityGroup.ts, nodejs/aws-infra/experimental/ec2/securityGroupRule.ts, nodejs/aws-infra/experimental/ec2/subnet.ts, nodejs/aws-infra/experimental/ec2/vpc.ts, nodejs/aws-infra/experimental/ec2/vpcTopology.ts, nodejs/aws-infra/experimental/ecs/cluster.ts, nodejs/aws-infra/experimental/ecs/ec2Service.ts, nodejs/aws-infra/experimental/ecs/fargateService.ts, nodejs/aws-infra/experimental/ecs/taskDefinition.ts, nodejs/aws-infra/experimental/elasticloadbalancingv2/application.ts, nodejs/aws-infra/experimental/elasticloadbalancingv2/listener.ts, nodejs/aws-infra/experimental/elasticloadbalancingv2/listenerRule.ts, nodejs/aws-infra/experimental/elasticloadbalancingv2/loadBalancer.ts, nodejs/aws-infra/experimental/elasticloadbalancingv2/network.ts, nodejs/aws-infra/experimental/elasticloadbalancingv2/targetGroup.ts, nodejs/aws-infra/network.ts, nodejs/tslint.json
Not ready for review.  Pushing this to get test coverage.
=> Introduce an abstraction for VPCs

nodejs/aws-infra/experimental/ec2/subnet.ts, nodejs/aws-infra/experimental/ec2/vpc.ts
Fixes https://github.com/pulumi/pulumi-aws-infra/issues/85
=> Include vpc name when creating subnets.

nodejs/aws-infra/network.ts
this PR adds back the public attribute added in #10
=> expose public routetable id

CHANGELOG.md, nodejs/awsx/ec2/index.ts, nodejs/awsx/ec2/internetGateway.ts, nodejs/awsx/ec2/natGateway.ts, nodejs/awsx/ec2/subnet.ts, nodejs/awsx/ec2/vpc.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/139
=> Make it possible to easily add an Internet Gateway to a vpc

CHANGELOG.md, nodejs/awsx/ecs/fargateService.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/188
=> Fix fargate memory/cpu computation

nodejs/awsx/tsconfig.json
Fixes https://github.com/pulumi/pulumi-awsx/issues/194
=> Add files to tsconfig to make sure we build docs for them.

CHANGELOG.md, nodejs/awsx/apigateway/api.ts, nodejs/awsx/package.json
Fixes https://github.com/pulumi/pulumi-aws/issues/441
=> Use actual aws typings to more accurately describe our apigateway api.

CHANGELOG.md, nodejs/awsx/autoscaling/autoscaling.ts, nodejs/awsx/autoscaling/index.ts, nodejs/awsx/autoscaling/schedule.ts, nodejs/awsx/tsconfig.json, nodejs/examples/ec2/update2/ec2.ts
Next up will be providing more complex scaling policies.
=> Add the ability to define a schedule for scaling an ASG.

CHANGELOG.md, nodejs/awsx/apigateway/api.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/253
=> Allow control over the bucket that gets created to contain static routes

CHANGELOG.md, nodejs/awsx/apigateway/api.ts, nodejs/awsx/autoscaling/launchConfiguration.ts, nodejs/awsx/aws_test.go, nodejs/awsx/ec2/subnet.ts, nodejs/awsx/ecr/index.ts, nodejs/awsx/ecr/lifecyclePolicy.ts, nodejs/awsx/ecr/repository.ts, nodejs/awsx/ecr/repositoryImage.ts, nodejs/awsx/ecs/container.ts, nodejs/awsx/ecs/image.ts, nodejs/awsx/ecs/service.ts, nodejs/awsx/elasticloadbalancingv2/listener.ts, nodejs/awsx/elasticloadbalancingv2/loadBalancer.ts, nodejs/awsx/index.ts, nodejs/awsx/tsconfig.json, nodejs/examples/ecr/Pulumi.yaml, nodejs/examples/ecr/README.md, nodejs/examples/ecr/app/Dockerfile, nodejs/examples/ecr/app/Dockerfile-multistage, nodejs/examples/ecr/app/content/index.html, nodejs/examples/ecr/index.ts, nodejs/examples/ecr/package.json, nodejs/examples/ecr/tsconfig.json
Enhancements to make it easier to:
1. create repositories.
2. set policies for a repository.
3. build and push docker images to a repo.
Note: this is a draft.  I need to still try this out to see how it feels.  We also need lots of testing here.
=>  Add ECR module. 

nodejs/awsx/ecs/ec2Service.ts, nodejs/awsx/ecs/fargateService.ts, nodejs/awsx/ecs/taskDefinition.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/271#event-2341525466
=> Properly support 'tags' in our derived types

nodejs/awsx/ec2/vpc.ts, nodejs/awsx/package.json, nodejs/awsx/utils.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/276
=>  Dynamically determine the number of availability zones for a VPC to use.

nodejs/awsx/apigateway/api.ts, nodejs/awsx/cloudwatch/README.md, nodejs/awsx/cloudwatch/widgets_json.ts, nodejs/awsx/package.json
=> Cloudwatch docs

nodejs/awsx/ec2/securityGroup.ts, nodejs/awsx/ec2/vpc.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/272
=> Add some helpful docs on what our fromXXX functions do.

CHANGELOG.md, nodejs/awsx/cloudwatch/dashboard.ts, nodejs/awsx/package.json, nodejs/examples/dashboards/index.ts, nodejs/examples/dashboards/package.json
Fixes https://github.com/pulumi/pulumi-awsx/issues/304
=> Publish dashboard url

CHANGELOG.md, nodejs/awsx/apigateway/api.ts, nodejs/awsx/aws_test.go, nodejs/awsx/elasticloadbalancingv2/application.ts, nodejs/awsx/elasticloadbalancingv2/index.ts, nodejs/awsx/elasticloadbalancingv2/listener.ts, nodejs/awsx/elasticloadbalancingv2/loadBalancer.ts, nodejs/awsx/elasticloadbalancingv2/targetGroup.ts, nodejs/awsx/elasticloadbalancingv2/targetGroupAttachment.ts, nodejs/awsx/tsconfig.json, nodejs/examples/alb/ec2Instance/Pulumi.yaml, nodejs/examples/alb/ec2Instance/README.md, nodejs/examples/alb/ec2Instance/index.ts, nodejs/examples/alb/ec2Instance/package.json, nodejs/examples/alb/ec2Instance/tsconfig.json, nodejs/examples/alb/lambdaTarget/Pulumi.yaml, nodejs/examples/alb/lambdaTarget/README.md, nodejs/examples/alb/lambdaTarget/index.ts, nodejs/examples/alb/lambdaTarget/package.json, nodejs/examples/alb/lambdaTarget/tsconfig.json
Fixes https://github.com/pulumi/pulumi-awsx/issues/294
=> Add the ability to easily attach targets to an ALB/NLB

CHANGELOG.md, nodejs/awsx/ecs/fargateService.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/360
=> Properly respect subnets in a FargateService if they are passed in.

nodejs/examples/alb/ec2/index.ts, nodejs/examples/alb/ec2Instance/index.ts, nodejs/examples/cluster/index.ts, nodejs/examples/ec2/update1/ec2.ts, nodejs/examples/ec2/update2/ec2.ts, nodejs/examples/metrics/index.ts
Fixes: #384
This is due to us-west-2d not supporting t2 instance types
=> Update examples instance types

nodejs/awsx/ec2/securityGroupRule.ts, nodejs/awsx/package.json, nodejs/awsx/tests/package.json, nodejs/examples/alb/ec2/package.json, nodejs/examples/alb/ec2Instance/index.ts, nodejs/examples/alb/ec2Instance/package.json, nodejs/examples/alb/fargate/package.json, nodejs/examples/alb/lambdaTarget/package.json, nodejs/examples/api/package.json, nodejs/examples/cluster/package.json, nodejs/examples/dashboards/package.json, nodejs/examples/ec2/package.json, nodejs/examples/ecr/package.json, nodejs/examples/metrics/package.json, nodejs/examples/nlb/fargate/package.json, nodejs/examples/nlb/fargateShort/package.json, nodejs/examples/vpc/package.json
Fixes https://github.com/pulumi/pulumi-awsx/issues/387
=> Fix ipv6 constant

CHANGELOG.md, nodejs/awsx/ecs/container.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/422.
Also added some docs to all properties.
Note: there is no runtime change here.  It's just a matter of updating our TS shapes to add the missing `secrets` prop.
=> Update our TS shape for containers to include 'secrets' prop.

CHANGELOG.md, nodejs/awsx/ecs/container.ts
=> Add missing Container properties

nodejs/awsx/cloudwatch/widgets_annotations.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/462
=> Update awsx to deal with change in 'aws' resource shape.

nodejs/examples/api/index.ts
Part of https://github.com/pulumi/pulumi-aws/issues/774
=> Update NodeJS version to 10.x in Lambda example

CHANGELOG.md, nodejs/awsx/ecs/container.ts
Fixes: #490
This is defined in https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html
=> Addition of FirelensConfiguration to the container

nodejs/awsx/ec2/vpc.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/505
=> Re-add a couple of Vpc members that were lost when we moved to making Vpc's asynchronous.

CHANGELOG.md, nodejs/awsx/ecs/cluster.ts, nodejs/awsx/ecs/ec2Service.ts, nodejs/awsx/ecs/fargateService.ts, nodejs/awsx/ecs/service.ts
=> Update ECS with latest upstream service and cluster args

CHANGELOG.md, nodejs/awsx/ecs/service.ts
=> Ensure any custom options are passed to underlying ecs Service when using awsx

CHANGELOG.md, nodejs/awsx/apigateway/api.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/529
=> Account for Windows paths in static routes for API Gateway

.github/workflows/artifact-cleanup.yml, .github/workflows/command-dispatch.yml, .github/workflows/pull-request.yml, .github/workflows/run-acceptance-tests.yml
Fixes: #584
This will mean that when a PR is opened, linting and an initial
build of the binaries will be performed to ensure there are no
obvious error.
The PR will have a comment added to it suggesting that the user needs
a maintainer to run the acceptance tests. The maintainer will run
the command /run-acceptance-tests and will wait for the results
This will trigger a full end-to-end set of tests including spinning
up the test infrastructure.
It is super important that the PR is checked that no secrets etc are
leaked before running the test command
Please note, as this is a command dispatch, this cannot be tested from
a PR - it must be in master and we can interate there!
=> Moving to a command dispatch for PRs

.github/workflows/master.yml
=> Adding a cron build to ensure that provider breakages are picked up

nodejs/awsx/apigateway/README.md
Fixes https://github.com/pulumi/docs/issues/4856
=> Fix broken link to awsx api gateway example

CHANGELOG.md, nodejs/awsx/aws_test.go, nodejs/awsx/ecs/ec2Service.ts, nodejs/awsx/ecs/fargateService.ts, nodejs/examples/task-definitions-with-proxy-config/.gitignore, nodejs/examples/task-definitions-with-proxy-config/Pulumi.yaml, nodejs/examples/task-definitions-with-proxy-config/index.ts, nodejs/examples/task-definitions-with-proxy-config/package.json, nodejs/examples/task-definitions-with-proxy-config/tsconfig.json
=> Add support for `proxyConfiguration` to `awsx.ecs.FargateTaskDefinition` and `awsx.ecs.EC2TaskDefinition`

CHANGELOG.md, nodejs/awsx/lb/targetGroup.ts, nodejs/awsx/package-lock.json
This is a copy paste of #503 to be able to run tests - going to merge this and close the other
=> Implement ListenerActions in TargetGroup

CHANGELOG.md, nodejs/awsx/apigateway/api.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/627
=> Create an explicit RestApiPolicy if a policy is specified

CHANGELOG.md, nodejs/awsx/ecs/ec2Service.ts, nodejs/awsx/ecs/fargateService.ts
=> Add ability to pass forceNewDeployment to ecs.FargateService ecs.Ec2Service

CHANGELOG.md, nodejs/awsx/ec2/subnet.ts, nodejs/awsx/ecs/container.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/682
=> Add environmentFile to container definition type

CHANGELOG.md, nodejs/awsx/lb/loadBalancer.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/690
=> Allow subnetMappings in load balancer args

nodejs/examples/api/index.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/714
=> Update NodeJS runtime version in apigateway example

CHANGELOG.md, nodejs/awsx/ec2/cidr.ts, nodejs/awsx/ec2/vpc.ts
I have been reading the AWS Crosswalk code and noticed these minor spelling mistakes and other bits and thought i'd submit a PR to fix them.
I have also updated the `CHANGELOG.md` as there was no `CHANGELOG_PENDING.md` as per https://github.com/pulumi/pulumi/blob/master/CONTRIBUTING.md#submitting-a-pull-request
=> Rectify some spelling mistakes

nodejs/awsx/ec2/README.md
Fix a spelling mistake: "workin" -> working.
=> Fix spelling mistake

awsx/package.json
This is now a full dependency as this is a provider dep
=> Remove peer_dependencies from the provider

.github/workflows/master.yml, .github/workflows/run-acceptance-tests.yml, scripts/prep-for-goreleaser.sh, scripts/publish_packages.sh
=> [internal] Publish SDK version on master builds

awsx/schema-types.ts, awsx/scripts/generate-provider-types.ts
- Allow a generic type to be used with getData.
=> Generate generic parameters

Makefile, awsx/babel.config.js, awsx/package.json, awsx/schema-types.ts, awsx/utils.test.ts, awsx/utils.ts
Fix bug in utils with first example test!
=> Set up unit testing

Makefile
Means all package dependencies are auto-synced from the provider package spec.
=> Auto-sync go SDK dependency

awsx/schema-types.ts, awsx/schema.json, schemagen/pkg/gen/lb.go, sdk/dotnet/Lb/NetworkLoadBalancer.cs, sdk/go/awsx/lb/networkLoadBalancer.go, sdk/nodejs/lb/networkLoadBalancer.ts, sdk/python/pulumi_awsx/lb/network_load_balancer.py
Was getting removed from inputs rather than outputs (was never added to inputs).
=> Remove default security group output on NLB

Makefile, schemagen/go.mod, schemagen/go.sum, sdk/go/awsx/cloudtrail/trail.go, sdk/go/awsx/ec2/vpc.go, sdk/go/awsx/ecr/repository.go, sdk/go/awsx/ecs/ec2service.go, sdk/go/awsx/ecs/ec2taskDefinition.go, sdk/go/awsx/ecs/fargateService.go, sdk/go/awsx/ecs/fargateTaskDefinition.go, sdk/go/awsx/ecs/pulumiTypes.go, sdk/go/awsx/lb/applicationLoadBalancer.go, sdk/go/awsx/lb/networkLoadBalancer.go, sdk/go/awsx/lb/pulumiTypes.go
Upgrade pulumi in schemagen to fix go SDK generation bugs
=> Fix Go codegen

awsx/schema-types.ts, awsx/schema.json, schemagen/pkg/gen/ec2.go, sdk/dotnet/Ec2/Vpc.cs, sdk/go/awsx/ec2/vpc.go, sdk/nodejs/ec2/vpc.ts, sdk/python/pulumi_awsx/ec2/vpc.py
Makes it much easier to use the outputs to inputs of other things
=> Make all VPC outputs required

awsx/ec2/subnetDistributor.test.ts, awsx/ec2/subnetDistributor.ts, awsx/ec2/subnetsIntegration.test.ts, awsx/ec2/vpc.test.ts, examples/examples_nodejs_test.go, examples/vpc/nodejs/vpc-multiple-similar-subnet-types/Pulumi.yaml, examples/vpc/nodejs/vpc-multiple-similar-subnet-types/index.ts, examples/vpc/nodejs/vpc-multiple-similar-subnet-types/package.json, examples/vpc/nodejs/vpc-multiple-similar-subnet-types/tsconfig.json
=> Fix up CIDR block calculation for more advanced subnet configs.

awsx/package.json, awsx/tsconfig.json, awsx/yarn.lock, examples/ts-lb-attach-ec2/package.json, examples/ts-lb-attach-lambda/package.json, examples/ts-lb-simple/package.json, examples/ts-lb-with-subnets/package.json, examples/ts-nlb-simple/package.json
Version mismatch may have been causing failures
=> Upgrade AWS version in examples

Makefile, awsx/PulumiPlugin.yaml, awsx/ec2/subnetDistributor.ts, awsx/ec2/vpc.ts
=> Fix up validation of vpc configuration types

Makefile
=> [internal] Add support for Linux arm64 packages

.github/workflows/master.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml, .github/workflows/run-acceptance-tests.yml, awsx/schema.json, schemagen/pkg/gen/schema.go, sdk/nodejs/package.json
Add ldid dependency for signing darwin arm binaries.
=> Add ldid for binary signing

awsx/ecr/repository.ts
I think this will fix #866 ?
Happy to do add any more to the PR if necessary
=> Makes lifecycle policy child of the repository

awsx-classic/cloudwatch/widgets_json.ts, awsx-classic/cloudwatch/widgets_simple.ts, sdk/nodejs/classic/cloudwatch/widgets_json.ts, sdk/nodejs/classic/cloudwatch/widgets_simple.ts
Adding in types to aws-classic. Fixes #888
=> Adding in types to aws-classic. Fixes issue #888

awsx/ec2/subnetDistributor.test.ts, awsx/ec2/subnetDistributor.ts, awsx/ec2/subnetsIntegration.test.ts, awsx/schema-types.ts, awsx/schema.json, schemagen/pkg/gen/ec2.go, sdk/dotnet/Ec2/Inputs/SubnetSpecArgs.cs, sdk/go/awsx/ec2/pulumiTypes.go, sdk/java/src/main/java/com/pulumi/awsx/ec2/inputs/SubnetSpecArgs.java, sdk/nodejs/types/input.ts, sdk/python/pulumi_awsx/ec2/_inputs.py
=> awsx.ec2.Vpc: Allow setting tags in subnetsSpecs

CHANGELOG.md, awsx/ecs/ec2TaskDefinition.test.ts, awsx/ecs/ec2TaskDefinition.ts, awsx/schema-types.ts, awsx/schema.json, schemagen/pkg/gen/ecsx.go, sdk/dotnet/Ecs/EC2Service.cs, sdk/go/awsx/ecs/ec2service.go, sdk/java/src/main/java/com/pulumi/awsx/ecs/EC2Service.java, sdk/java/src/main/java/com/pulumi/awsx/ecs/EC2ServiceArgs.java, sdk/nodejs/ecs/ec2service.ts, sdk/python/pulumi_awsx/ecs/ec2_service.py
Fixes #942
Possible breaking change for Go users as it changes the type?
=> Allow overriding of networkMode

CHANGELOG.md, awsx/ecs/fargateService.ts, awsx/package.json, awsx/schema-types.ts, awsx/schema.json, awsx/yarn.lock, examples/ecs/dotnet/MyStack.cs, examples/ecs/python/__main__.py, examples/ts-lb-simple/index.ts, examples/ts-lb-with-subnets/index.ts, schemagen/pkg/gen/ecsx.go, schemagen/pkg/gen/schema.go, sdk/dotnet/Ecs/FargateService.cs, sdk/go/awsx/ecs/fargateService.go, sdk/java/src/main/java/com/pulumi/awsx/ecs/FargateServiceArgs.java, sdk/nodejs/ecs/fargateService.ts, sdk/nodejs/package.json, sdk/python/pulumi_awsx/ecs/fargate_service.py
=> Default FargateService to non-public

.github/workflows/command-dispatch.yml, CHANGELOG.md
slash-command-dispatch updated to v3
=> ci: command-dispatch Updates to v3

examples/ts-ecr-simple/package.json, examples_legacy/alb/ec2/package.json, examples_legacy/alb/ec2Instance/package.json, examples_legacy/alb/fargate/package.json, examples_legacy/alb/fargateInlineListener/package.json, examples_legacy/alb/lambdaTarget/package.json, examples_legacy/api/package.json, examples_legacy/cluster/package.json, examples_legacy/dashboards/package.json, examples_legacy/ec2/package.json, examples_legacy/ecr/package.json, examples_legacy/metrics/package.json, examples_legacy/nlb/fargate/package.json, examples_legacy/nlb/fargateShort/package.json, examples_legacy/nlb/fargateShortInlineListener/package.json, examples_legacy/vpc/package.json, examples_legacy/vpcIgnoreSubnetChanges/package.json
Fixes integration tests for latest pulumi CLI version
=> Remove erroneous main package field

examples/cloudtrail/nodejs/index.ts
=> Expand CloudTrail example with bucket encryption variants

awsx/ecs/fargateMemoryAndCpu.test.ts, awsx/ecs/fargateMemoryAndCpu.ts
=> Update max CPU and memory for Fargate, add tests

awsx/yarn.lock
Combining multiple dependencies PRs into one.
<details>
<summary>Instructions for merging</summary>
* **Use a merge commit**, so that GitHub will mark all original PRs as merged.
* If your repository does not have merge commits enabled, please temporarily enable them in settings. Tick `Allow merge commits` in the repository settings.
* When ready, merge this PR using `Create a merge commit`.
</details>
* Bump semver from 5.7.1 to 5.7.2 in /awsx (#1041) @app/dependabot
* Bump json5 from 2.2.1 to 2.2.3 in /awsx (#973) @app/dependabot
=> Combined Dependabot upgrades

sdk/python/README.md
=> Fixup python README

awsx/schema.json, schemagen/pkg/gen/ecsx.go, sdk/dotnet/Ecs/FargateService.cs, sdk/go/awsx/ecs/fargateService.go, sdk/java/src/main/java/com/pulumi/awsx/ecs/FargateServiceArgs.java, sdk/nodejs/ecs/fargateService.ts, sdk/python/pulumi_awsx/ecs/fargate_service.py
=> Override AWS doc string that's incorrect for AWSx

examples/ts-lb-with-subnets/index.ts
Use a transformation to set the create custom timeout.
Fixes https://github.com/pulumi/pulumi-awsx/issues/1104
=> Extend ECS service create timeout

Makefile, awsx/package.json, awsx/yarn.lock, schema.json, sdk/java/build.gradle, sdk/nodejs/package.json, sdk/python/setup.py
- Add missing makefile dependency. Codegen reads dependencies from package.json to generate the schema.
Fixes #1160
=> Upgrade docker to 4.5.0

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, CONTRIBUTING.md, devbox.json, devbox.lock
Adds devbox and devcontainer config files along with instructions for using them. Prompted by a user request for a devcontainer config for this repo:
Resolves https://github.com/pulumi/pulumi-awsx/issues/1200
=> Add devbox  and devcontainer support

awsx/package.json, awsx/yarn.lock, schema.json, sdk/java/build.gradle, sdk/nodejs/package.json, sdk/python/pyproject.toml
Upgrade the pinned docker dependency to 4.5.1.
Fixes: #1219
=> bump docker version to 4.5.1

awsx/ecr/image.ts, awsx/schema-types.ts, devbox.lock, schema.json, schemagen/pkg/gen/ecr.go, sdk/dotnet/Ecr/Image.cs, sdk/go/awsx/ecr/image.go, sdk/go/awsx/ecr/pulumiTypes.go, sdk/java/src/main/java/com/pulumi/awsx/ecr/ImageArgs.java, sdk/nodejs/ecr/image.ts, sdk/python/pulumi_awsx/ecr/image.py
Internal copy of https://github.com/pulumi/pulumi-awsx/pull/1229 to enable tests
=> Add imageTag parameter to ecr image resource v2

.github/workflows/cron.yml, .github/workflows/master.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml
Propagate disk space workaround from PRs to all other workflows.
=> Free disk space

Makefile
=> Revert skipped tests

examples/examples_nodejs_test.go
Fixes https://github.com/pulumi/pulumi-awsx/issues/1404
Relates: https://github.com/pulumi/pulumi-awsx/issues/1382
=> Skip IPAM tests until sharing is figured out

Makefile, renovate.json5
I tried to copy what we did for pulumi-eks to generate the missing
files.
re #1451
=> chore: generate files as part of renovate

Makefile
Looks like there was another make target that generates stuff
re #1461
=> chore: fix renovate

.github/workflows/weekly-pulumi-update.yml
Fixes https://github.com/pulumi/pulumi-awsx/issues/1474 P1
Applying a known workaround to a GitHub CLI issue.
=> chore: fix weekly-pulumi-update

.github/workflows/build_provider.yml
Applies https://github.com/pulumi/ci-mgmt/pull/1296 proactively.
Fixes https://github.com/pulumi/pulumi-awsx/issues/1490
=> Fix binary signing for darwin-arm64

.github/workflows/awsx-weekly-pulumi-update.yml
Quick fix for https://github.com/pulumi/pulumi-awsx/issues/1495
=> Update dependent files via make renovate

awsx/package.json, awsx/yarn.lock, provider/cmd/pulumi-resource-awsx/schema.json, sdk/java/build.gradle, sdk/nodejs/package.json, sdk/python/pyproject.toml
=> Bump docker-build
