pulumi/pulumi-awsx

- .gitignore
- python/pulumi_aws_infra/__init__.py
- python/pulumi_aws_infra/network.py
- python/pulumi_aws_infra/util.py
- python/setup.py
This code came out of last Thursday's hackathon and serves as an example and test that we can write non-trivial components in Python.
This code is translated pretty much verbatim from the TypeScript implementation in this repo. All of this code is known to work with tip-of-master builds of `pulumi` and `pulumi-aws`, but we'll need to do another pass once the `v0.14` SDK drops.
Follow-up PRs will do the plumbing required to publish this package to PyPI.
> Add aws-infra Network implementation in Python

- nodejs/aws-infra/examples/cluster/package.json
- nodejs/aws-infra/package.json
This gets rid of all the:
```
warning package.json: License should be a valid SPDX license expression
warning @pulumi/aws-infra@${VERSION}: License should be a valid SPDX license expression
```
messages that show up while building.
> Update licenses in package.json files.

- .travis.yml
- Gopkg.lock
- Gopkg.toml
- nodejs/aws-infra/examples/cluster/package.json
- nodejs/aws-infra/examples/cluster/yarn.lock
- nodejs/aws-infra/network.ts
- nodejs/aws-infra/package.json
- nodejs/aws-infra/yarn.lock
In preperation for 0.15.0-rc1, adopt the newest versions of some
packages from master and deal with the fallout (there was a breaking
change in @pulumi/aws that will be part of 0.15.0-rc1).
> Update aws package to latest

- nodejs/aws-infra/examples/cluster/package.json
NPM and some other packages (including read-package-json that
@pulumi/pulumi) uses require the version field to be a valid
semver. So ensure ours are.
> Make test package versions valid semvers

- nodejs/aws-infra/cluster.ts
- nodejs/aws-infra/experimental/autoscaling/autoscaling.ts
- nodejs/aws-infra/experimental/clusterFileSystem.ts
- nodejs/aws-infra/experimental/ec2/securityGroup.ts
- nodejs/aws-infra/experimental/ec2/securityGroupRule.ts
- nodejs/aws-infra/experimental/ecs/cluster.ts
- nodejs/aws-infra/experimental/ecs/ec2Service.ts
- nodejs/aws-infra/experimental/ecs/fargateService.ts
- nodejs/aws-infra/experimental/ecs/service.ts
- nodejs/aws-infra/experimental/ecs/taskDefinition.ts
- nodejs/aws-infra/experimental/elasticloadbalancingv2/application.ts
- nodejs/aws-infra/experimental/elasticloadbalancingv2/listener.ts
- nodejs/aws-infra/experimental/elasticloadbalancingv2/listenerRule.ts
- nodejs/aws-infra/experimental/elasticloadbalancingv2/loadBalancer.ts
- nodejs/aws-infra/experimental/elasticloadbalancingv2/network.ts
- nodejs/aws-infra/experimental/elasticloadbalancingv2/targetGroup.ts
- nodejs/aws-infra/package.json
Update rules;
1. Components don't need to pass 'props' to super.  They can pass props, but they will be ignored.  To make this clearer, we explicitly pass `{}` down.
2. Non-abstract subclasses should call `.registerOutputs()` at the end of their constructor.  There is no need to pass arguments here.  Those are only needed for 'Stack' to register its exported outputs.
> Update components to follow new design rules.

- nodejs/aws-infra/examples/ec2/package.json
- nodejs/aws-infra/examples/fargate/package.json
- nodejs/aws-infra/experimental/elasticloadbalancingv2/targetGroup.ts
- nodejs/aws-infra/package.json
The `port` property can now be undefined on aws TargetGroups when a Lambda is targetted.  It is not possible for the TargetGroup created by this wrapper to create the Lambda type yet though, so we can just assert the undefined away.
Also updates dependencies to fixed released versions for package and floating released versions for tests - instead of `dev`.
Fixes #83.
> Adopt breaking change from AWS provider

- nodejs/aws-infra/cluster.ts
- nodejs/aws-infra/experimental/autoscaling/autoscaling.ts
- nodejs/aws-infra/experimental/ec2/vpc.ts
- nodejs/aws-infra/experimental/ecs/cluster.ts
- nodejs/aws-infra/experimental/ecs/ec2Service.ts
- nodejs/aws-infra/experimental/ecs/fargateService.ts
- nodejs/aws-infra/experimental/ecs/image.ts
- nodejs/aws-infra/experimental/ecs/service.ts
- nodejs/aws-infra/experimental/ecs/taskDefinition.ts
- nodejs/aws-infra/experimental/role.ts
- nodejs/aws-infra/network.ts
Fix several places where we were not accepting a `ComponentResourceOptions` as needed to enable component-based provider chaining.
> Accept ComponentResourceOptions

- nodejs/aws-infra/aws_test.go
- nodejs/aws-infra/examples/ec2/index.ts
- nodejs/aws-infra/examples/fargate/index.ts
- nodejs/aws-infra/experimental/ecs/service.ts
- nodejs/aws-infra/experimental/ecs/taskDefinition.ts
This removes some of the `cloud` leftovers of the `run` implementation, and instead aligns fully with the awssdk `runTask` function.
We use a similar trick to override the awssdk args interface with a slightly modified one that can infer more inputs from the `cluster` and `task`.
Fixes #80.
> Expose a more flexibe `runTask` on TaskDefinition

- nodejs/aws-infra/examples/fargate/index.ts
- nodejs/aws-infra/experimental/autoscaling/autoscaling.ts
- nodejs/aws-infra/experimental/clusterFileSystem.ts
- nodejs/aws-infra/experimental/ec2/securityGroup.ts
- nodejs/aws-infra/experimental/ec2/securityGroupRule.ts
- nodejs/aws-infra/experimental/ec2/subnet.ts
- nodejs/aws-infra/experimental/ec2/vpc.ts
- nodejs/aws-infra/experimental/ec2/vpcTopology.ts
- nodejs/aws-infra/experimental/ecs/cluster.ts
- nodejs/aws-infra/experimental/ecs/ec2Service.ts
- nodejs/aws-infra/experimental/ecs/fargateService.ts
- nodejs/aws-infra/experimental/ecs/service.ts
- nodejs/aws-infra/experimental/ecs/taskDefinition.ts
- nodejs/aws-infra/experimental/elasticloadbalancingv2/listener.ts
- nodejs/aws-infra/experimental/elasticloadbalancingv2/listenerRule.ts
- nodejs/aws-infra/experimental/elasticloadbalancingv2/loadBalancer.ts
- nodejs/aws-infra/experimental/elasticloadbalancingv2/targetGroup.ts
1. Use a name that matches the underlying resource type instead of 'instance'.
2. Elevate commonly accessed 'id' properties to component resource.
> Rename 'instance' fields.

- nodejs/aws-infra/experimental/autoscaling/autoscaling.ts
- nodejs/aws-infra/experimental/ec2/securityGroup.ts
- nodejs/aws-infra/experimental/ecs/cluster.ts
- nodejs/aws-infra/experimental/ecs/ec2Service.ts
- nodejs/aws-infra/experimental/ecs/fargateService.ts
- nodejs/aws-infra/experimental/ecs/service.ts
- nodejs/aws-infra/experimental/elasticloadbalancingv2/application.ts
- nodejs/aws-infra/experimental/elasticloadbalancingv2/loadBalancer.ts
This approach was introduced in https://github.com/pulumi/pulumi-aws-infra/commit/f45138ffc6a8a920aecb6195836c09bcc3864ceb.  However, it was not applied uniformly to all of aws-infra.  This PR does that.
> Use a consistent approach to security groups.

- nodejs/aws-infra/examples/ec2/index.ts
- nodejs/aws-infra/examples/fargate/index.ts
- nodejs/aws-infra/experimental/ecs/cluster.ts
- nodejs/aws-infra/experimental/ecs/container.ts
- nodejs/aws-infra/experimental/ecs/ec2Service.ts
- nodejs/aws-infra/experimental/ecs/fargateService.ts
- nodejs/aws-infra/experimental/ecs/service.ts
- nodejs/aws-infra/experimental/elasticloadbalancingv2/listener.ts
- nodejs/aws-infra/experimental/elasticloadbalancingv2/targetGroup.ts
This improves the consumption side of things for users by making the shapes of our APIs feel more natural.  For example, instead of saying:
```ts
containers: {
nginx: {
portMappings: myTargetGroup;
}
}
```
You instead say:
```ts
...
portMappings: [myTargetGroup]
...
```
i.e. instead of passing a singular 'target group' that then goes into the plural 'portMappings', you pass the singular group as an element of an array.  This makes the singular/plural shapes make more sense.
this also provides the user with more flexibility as they can place multiple elements in the array.  For example, tehy can place a raw port-mapping object in the array, or they can place a callback (like a target-group) in the array.  The array can be heterogeneous as well.  Raw-objects and callbacks can be in the same …
> Switch callback-interfaces to produce individual items, not arrays.

- nodejs/aws-infra/ecs/container.ts
- nodejs/aws-infra/ecs/image.ts
- nodejs/aws-infra/examples/ec2/index.ts
- nodejs/aws-infra/examples/fargate/index.ts
We really do not want to have caching in our infrastructure layers.  It makes ownership of resources much more complex, and produces all sorts of other problems (i.e. what to name things, when to reuse them).
It's cleaner to just produce resources on demand, clearly parented by an obvious root, and allow users to create caching themselves at their own layer (i.e. by making their own singleton object they could pass around as needed).
> Remove docker caching from awsinfra layer.

- nodejs/awsx/autoscaling/autoscaling.ts
This as added as a temporary measure to track something down in travis.  it was not intended to be committed.
> Remove old onFailure logic

- Gopkg.lock
- nodejs/awsx/package.json
This PR updates the required version of @pulumi/pulumi in `package.json`, and the various Go dependencies.
> Update various dependencies

- nodejs/awsx/elasticloadbalancingv2/network.ts
Needed the types changed to allow the following:
```
const worthTLSListener = worthTargetGroup.createListener("sandbox_worth_tls", {
port: 443,
protocol: "TLS",
certificateArn: worthCert.arn,
sslPolicy: "ELBSecurityPolicy-2016-08"
});
```
> Allow network listener to take TLS options.

- CHANGELOG.md
- nodejs/awsx/aws_test.go
- nodejs/awsx/ec2/natGateway.ts
We're not quite sure why this flag is necessary.  However, a customer was running into an issue in a particular region where not setting this made the EIPs into 'standard' ones instead of 'vpc' ones.  This fixes the problem with no apperant downsides (we always want 'vpc' EIPs here by definition, so being explicit doens't hurt).
> Explicitly set 'vpc' flag on EIP to ensure it is set to the right domain

- CHANGELOG.md
- nodejs/awsx/elasticloadbalancingv2/application.ts
- nodejs/awsx/package.json
Fixes https://github.com/pulumi/pulumi-awsx/issues/197
> If not specified, give an ALB a default security group so that AppListeners can add ingress/egress rules

- CHANGELOG.md
- nodejs/awsx/ec2/internetGateway.ts
- nodejs/awsx/ec2/vpc.ts
- nodejs/awsx/ec2/vpcTopology.ts
This reverts commit 84a713411b3f4d6d69ead30bd2d6af8edc1c8569.
We want to take this.  but it will need to come with a minor-version-bump for pulumi/awsx since we're changing parent/child relationships.
> Revert "Properly parent VPC resources. (#210)"

- nodejs/awsx/ec2/natGateway.ts
Fixes #267.
Per the docs, it appears that `natGatewayId` is the intended way to specify this - it's not clear why `gatewayId` was working to begin with - but it still appears to cause refresh cycle probems as seen in #267.
```ts
/**
* Identifier of a VPC internet gateway or a virtual private gateway.
*/
gatewayId?: pulumi.Input<string>;
/**
* Identifier of a VPC NAT gateway.
*/
natGatewayId?: pulumi.Input<string>;
```
> Use `natGatewayId` instead of `gatewayId` to specify NAT gateway route

- nodejs/awsx/ec2/cidr.ts
- nodejs/awsx/ec2/vpcTopology.ts
- nodejs/awsx/tests/ec2/ec2.spec.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/275
Note: this solely improves our error we give users here.  Instead of the cryptic:
`Cidr mask must be between "16" and "28" but was 30`
You get:
```
Error: Not enough address space in VPC to create desired subnet config.
VPC has 16 IPs, but is being asked to split into a total of 2 subnets.
2 subnets are necessary to have 2 AZ(s) each with 1 subnet(s) in them.
This needs 8 IPs/subnet, which is smaller than the minimum (16) allowed by AWS.
```
> Produce a better message when we can't partition the VPC cidr space to meet the user's desired config

- nodejs/awsx/cloudwatch/metric.ts
Build was failing with:
```
cloudwatch/metric.ts:333:16 - error TS2339: Property 'hasOwnProperty' does not exist on type 'T'.
333     return obj.hasOwnProperty(key);
```
> Fix build break

- nodejs/awsx/ecs/metrics.ts
- nodejs/awsx/rds/metrics.ts
- nodejs/awsx/s3/metrics.ts
Hugo's markdown renderer requires a blank line before lists in order for them to render correctly.
Follow-up from https://github.com/pulumi/docs/pull/1106 so we don't regress next time we generate the docs.
> Fix API doc markdown rendering issue

- nodejs/awsx/elasticloadbalancingv2/application.ts
- nodejs/awsx/elasticloadbalancingv2/loadBalancer.ts
- nodejs/awsx/elasticloadbalancingv2/network.ts
- nodejs/awsx/elasticloadbalancingv2/targetGroup.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/296
When we ported code down from 'cloud' we unfortunately kept some code that unnecessarily hashes an LB's name to produce the resource name for the actual cloud.  This leads to gibberish in the AWS console for those names, which isn't great.
We can't change this behavior due to the impact it would have on existing stacks.  So, for now, we allow a person to workaround this by explicitly providing the name they'd like to use like so:  `new ApplicationLoadBalancer("PreferredName", { name: "PreferredName" })`.
> Allow users to specify the names used for LBs and TGs

- nodejs/awsx/ec2/vpc.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/314
As mentioned in #314
> Easy to fix, but easy bug to make. I'm going to bring this up at our backcompat discussion tomorrow. If we're willing to break things, we might want to put on the table the idea of just outright moving to a model where "parent" is required. It's basically a footgun for us that keeps hitting us over and over again.
> Properly pass along parent when making invoke call.

- nodejs/awsx/ecs/fargateService.ts
There are two legal input formats for `memory` on `TaskDefinitions` - MB and GB.  However, internally AWS stores these in the MB format.   So specifying the value in GB leads to spruious refresh changes that force replacements.
Related to pulumi/pulumi#2821.
> Provide `memory` in MB for TaskDefinitions

- CHANGELOG.md
- nodejs/awsx/ec2/subnet.ts
- nodejs/awsx/ec2/vpc.ts
- nodejs/awsx/ec2/vpcTopology.ts
- nodejs/examples/vpc/index.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/323
An `awsx.ec2.Vpc` with `assignGeneratedIpv6CidrBlock: true` will now set  `assignIpv6AddressOnCreation: true` by default for child subnets.  This can be overridden by  setting that value explicitly to `false` with the subnet's args.
This changes our behavior and falls under:
https://github.com/pulumi/home/wiki/Compatibility-philosophy-and-guidelines: 
> Changes to existing resources. We may decide at times to change certain defaults for a resource. Or to add information into a resource (for example 'tags'). Because this has the potential to change runtime behavior, we should let customers know and provide them guidance on what to do if they don't want their resource to change (for example, by manually providing the old value).
> If it …
> Enable ipv6 for Vpc subnets.

- CHANGELOG.md
- nodejs/awsx/apigateway/api.ts
- nodejs/awsx/apigateway/swagger_json.ts
- nodejs/awsx/aws_test.go
- nodejs/examples/api/index.ts
I am working on my demo for Thursday and trying to enable CORS. To do this I need to create an OPTIONS endpoint, and be able to set a custom gateway response for the 401.
I would like to see an improved experience here, but for now this gets the job done:
```ts
routes: [{
path: "/hello",
method: "OPTIONS",
eventHandler: async () => {
return {
statusCode: 200,
body: "",
headers: {
"Access-Control-Allow-Origin": "*",
"Access-Control-Allow-Headers": "*",
},
};
},
},{
path: "/hello",
method: "GET",
eventHandler: async () => {
return {
statusCode: 200,
body: `{
"message": "hello"
}`,
headers: {
"Access-Control-Allow-Origin": "*",
"Access-Control-Allow-Headers": "*",
},
};
},
authorizers: awsx.apigateway.getTokenLambdaAuthorizer({
authorizerName: "jwt-rsa-custom-authorizer",
header: …
```
> Add OPTIONS and ability to set custom gateway responses

- nodejs/awsx/autoscaling/launchConfiguration.ts
Missed a case.  Caught by our "long" tests.
> Pass parent opts in another location.

- CHANGELOG.md
- nodejs/awsx/elasticloadbalancingv2/loadBalancer.ts
- nodejs/awsx/elasticloadbalancingv2/targetGroup.ts
Better fix for: https://github.com/pulumi/pulumi-awsx/issues/296
As per internal discussions, we're just going to use the real name a user passed along for the actual resource and not hash anything.
Thanks to aliases we can do this without actually causing changes.  I have tested this out and validated things.  For users that *do* want the resource to change names, tehy will need to pass in a new name.  This will cause recreations.  However, that's acceptable as that's the actual intent of the work.
> Do not hash LoadBalancer or TargetGroup names when creating them.

- nodejs/awsx/ec2/vpc.ts
This broke in https://github.com/pulumi/pulumi-awsx/commit/004393885a8dadae5301c00ee04e526004b5e381 (which has not shipped publicly yet).
previously we hardcoded in: 
```ts
const subnetIds = vpcId.then(id => aws.ec2.getSubnetIds({ vpcId: id }))
.then(subnets => subnets.ids);
const subnet0 = subnetIds.then(ids => ids[0]);
const subnet1 = subnetIds.then(ids => ids[1]);
const publicSubnetIds = [subnet0, subnet1];
```
Because i could move away from async to sync, i changed the above to:
```ts
const publicSubnetIds = utils.promiseResult(aws.ec2.getSubnetIds({ vpcId }, { provider }).then(subnets => subnets.ids))
```
We need to restore the original behavior as these public subnets are often queried to make other flow-control or other sorts of downstream decisions.
Note: we could always consider …
> Restore default around how many subnets we pull in for teh default Vpc for a region.

- nodejs/awsx/apigateway/api.ts
Each of these fields is populated by the AWS provider, and any
differences between the read values and the inputs will cause spurious
diffs.
- If `body` is specified, the `name` field will be populated from the
title present in the Swagger spec. Ensure that we fill in a matching
name by parsing the spec and extracting its title.
- If `binaryMediaTypes` is unspecified, it will be populated with
`[ "*/*" ]`, which causes a delete diff. To avoid this, just specify
`[ "*/*" ]` explicitly.
> Fill in name and binaryMediaTypes in RestApi.

- nodejs/awsx/ec2/vpc.ts
This fixes the issue causing awsx to not pass CI.
Note: this demonstrates a general issue we have with complex awsx resources.  We need to ensure each type we have is capturable.  I will open issue to have a test for exactly this.
Opened https://github.com/pulumi/pulumi-awsx/issues/364 to track test hole here.
> Fix issue causing clusters to not be serializable.

- CHANGELOG.md
- nodejs/awsx/apigateway/api.ts
- nodejs/awsx/ecs/cluster.ts
- nodejs/awsx/ecs/container.ts
- nodejs/awsx/ecs/ec2Service.ts
- nodejs/awsx/ecs/fargateService.ts
- nodejs/awsx/ecs/taskDefinition.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/344#event-2431687822
I did a sweep of `@pulumi/awsx` for cases where we allow users to pass in a resource, but where we then also produce a default for them if they give us 'nothing'.  Previously 'nothing' was  effectively defined as `null` or `undefined`.  This allowed a good balance of reasonable defaults with user flexibility to provide what they wanted.  However, with our existing system, there was no way to say "i don't want *anything* here".  No matter what you did, you would end up with a Resource. 
We now support the concept of `null` being a way for users to explicitly state that htey do not want a resource at all.  This allows users to do one of:
1. pass nothing (or explicit `undefined`).  In that case, they get a default …
> Add support for users opting out of our default resource creation.

- CHANGELOG.md
- nodejs/awsx/package.json
This causes us to require the version of `@pulumi/docker` which depends on `1.0.0-beta`
> Update `@pulumi/docker` version

- CHANGELOG.md
- nodejs/awsx/aws_test.go
- nodejs/awsx/ec2/subnet.ts
- nodejs/awsx/ec2/vpc.ts
- nodejs/awsx/ec2/vpcTopology.ts
- nodejs/examples/vpcIgnoreSubnetChanges/Pulumi.yaml
- nodejs/examples/vpcIgnoreSubnetChanges/index.ts
- nodejs/examples/vpcIgnoreSubnetChanges/package.json
- nodejs/examples/vpcIgnoreSubnetChanges/step2/index.ts
- nodejs/examples/vpcIgnoreSubnetChanges/tsconfig.json
Adds one-off support for passing ignoreChanges through to VPC Subnets. This unblocks a common use case where tags may be added outside of Pulumi and need to be ignored.
Longer-term, this will be solved instead via pulumi/pulumi#2068 which will allow customizing any options on child resources via transformation callbacks.
Fixes #398.
> Allow setting ignoreChanges on VPC Subnets

- CHANGELOG.md
- nodejs/awsx/apigateway/api.ts
Supercedes https://github.com/pulumi/pulumi-awsx/pull/416.
Fixes this part of: https://github.com/pulumi/pulumi-awsx/issues/417
> There's no way to select REGIONAL for the endpoint configuration
> Expose ways to customize the Deployment, RestApi and Stage produce by an apigateway.API

- nodejs/awsx/apigateway/README.md
This was pointed out by Patrick Flaherty in slack.  Looks like the awsx folder was removed under the examples.
> update link to example

- nodejs/awsx/ecs/ec2Service.ts
- nodejs/awsx/ecs/fargateService.ts
Fixes: #439
This will be passed down to the TaskDefiniton
> Allow the passing of (optional) family as a parameter to ec2Service

- nodejs/awsx/ecs/cluster.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/444
> Defer to user-provided security groups when creating an ASG from a Cluster

- README.md
- nodejs/awsx/apigateway/README.md
- nodejs/awsx/autoscaling/README.md
- nodejs/awsx/cloudwatch/README.md
- nodejs/awsx/ec2/README.md
- nodejs/awsx/lb/README.md
When these get pulled into the docs site, they currently render multiple H1 tags, which flags them in our SEO alerts. This just turns the `H1`s into `H2`s, and moves everything below them one level in.
> Fix duplicate H1 tags

- CHANGELOG.md
- nodejs/awsx/apigateway/api.ts
- Include the following outputs from the REST API
- API Key Source
- Binary Media Types
- Endpoint Configuration
- Minimum Compression Size
- Gateway Policy
- Swagger string containing route information
Including these arguments should trigger a redeployment of the API whenever any of the above change
Closes #485
> apigateway.Deployment - account for all args

- CHANGELOG.md
- nodejs/awsx/apigateway/api.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/485
- Include the following outputs from the REST API
- API Key Source
- Binary Media Types
- Endpoint Configuration
- Minimum Compression Size
- Gateway Policy
- Swagger string containing route information
Including these arguments should trigger a redeployment of the API whenever any of the above change
> Expand the set of parameters to an APIGateway that will force redeployment

- CHANGELOG.md
- nodejs/awsx/package.json
Fixes https://github.com/pulumi/pulumi-awsx/issues/495
> Update dependent version of @pulumi/pulumi to ensure it has an API we call.

- nodejs/awsx/lb/listener.ts
This is impacting a case where one of these resources is captured and used from an aws lambda.  We want to expose the outputs of this resource, but not hte methods that pull in pulumi modules that do not exist at cloud runtime.
> Add some deployment-time-only methods to the doNotCapture list.

- nodejs/awsx/ec2/README.md
Renames the security group to a valid name and adds the `awsx.ec2` namespace.
As "sg" the security group failed to be created with an error from AWS:
```
error: Error creating Security Group: InvalidParameterValue: Value (sg-017c251) for parameter GroupName is invalid. Group names may not be in the format sg-*.
```
> README change to rename security group to valid name

- CHANGELOG.md
- nodejs/awsx/ecs/container.ts
- nodejs/awsx/ecs/ec2Service.ts
- nodejs/awsx/ecs/fargateService.ts
- nodejs/awsx/ecs/taskDefinition.ts
> Allow nullable logGroup, taskRole, and executionRole for TaskDefinitionArgs, EC2TaskDefinitionArgs, and FargateTaskDefinitionArgs

- CHANGELOG.md
- nodejs/awsx/ecs/taskDefinition.ts
When `taskRole` is passed as `null` but `executionRole` is provided, `TaskDefinition` wrongly test another parameter and does not accept the execution role. This causes errors such as `Fargate requires task definition to have execution role ARN to support ECR images.`.
> Fix checking of executionRole in TaskDefinition

- CHANGELOG.md
- nodejs/awsx/lb/application.ts
- nodejs/awsx/lb/loadBalancer.ts
- nodejs/awsx/lb/network.ts
Updated version of @eordano's https://github.com/pulumi/pulumi-awsx/pull/541 based on code review feedback from @leezen. 
@eordano I hope you don't mind me taking this initiative. I'm in desperate need of this feature, so wanted to lend a hand to move things quickly if possible
Closes https://github.com/pulumi/pulumi-awsx/pull/541
Closes https://github.com/pulumi/pulumi-awsx/issues/535
Closes https://github.com/pulumi/pulumi-awsx/issues/543
Closes https://github.com/pulumi/pulumi-aws/issues/824
The Travis failure is coming from `cloudwatch` and looks unrelated to this PR
> Creation of awsx LoadBalancer from aws LoadBalancer

- CHANGELOG.md
- nodejs/awsx/lb/application.ts
- nodejs/awsx/lb/listener.ts
- nodejs/awsx/lb/network.ts
Ok, so I've made it a bit farther, but it turns out that https://github.com/pulumi/pulumi-awsx/pull/548 alone really wasn't enough and we need to do the same for the listener. In fact the only reason I need the load balancer is to pass it in via the args when constructing the listener
I have an infra project where I'm setting up common resources like the database and load balancer. And then a frontend sub-project and backend sub-project. Both of the sub-projects will need to setup their routes with the application load balancer listener and then pass the listener to the fargate service
> Creation of awsx Listener from aws Listener

- nodejs/awsx/ecr/repository.ts
Related to https://github.com/pulumi/docs/issues/3870.
The parentheses leads to markdown that literally links to `https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/awsx/ecr/optionally configured using [args]`.
You can find this broken link for `Repository` resource in https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/awsx/ecr/#buildAndPushImage.
> Fix a doc comment that causes an improperly formatted link in the lang docs

- CHANGELOG.md
- nodejs/awsx/lb/application.ts
- nodejs/awsx/lb/network.ts
- nodejs/awsx/lb/targetGroup.ts
Wrapping up from pulumi/pulumi-awsx#553 and https://github.com/pulumi/pulumi-awsx/pull/548. This is the last piece of the puzzle for rehydrating a load balancer
(fwiw, I've actually decided to architect my app a different way, but it seems good to wrap up this outstanding work since the previous PRs can't be used without this one)
> Creation of awsx TargetGroup from aws TargetGroup

- nodejs/awsx/lb/application.ts
Fixes the build for AWS 3.16.0 which allows an undefined port on the listener.
> Account for undefined port on LB Listener

- CHANGELOG.md
- nodejs/awsx/lb/network.ts
- nodejs/awsx/lb/targetGroup.ts
Based on https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health-checks.html it's possible to set the path and matcher for NLB target group health checks.
Fixes https://github.com/pulumi/pulumi-awsx/issues/605
> Update NetworkTargetGroupHealthCheck to match specification

- CHANGELOG.md
- nodejs/awsx/ecs/container.ts
- nodejs/awsx/ecs/service.ts
- nodejs/awsx/ecs/taskDefinition.ts
The awsx.ecs types have drifted a little relative to the aws.ecs types.  This change brings them up to date with the latest types in the AWS package.  In particular this adds:
* `Container#interactive`
* `ServiceArgs#forceNewDeployment`
* `TaskDefinitionArgs#inferenceAccelerators`
* `TaskDefinitionArgs#ipcMode`
* `TaskDefinitionArgs#pidMode`
* `TaskDefinitionArgs#proxyConfiguration`
Aside: The implementation includes an Override type that attempts to derive the correct type from the upstream types.  If this had been used directly, it would have avoided the need for this maintenance.  But documentation and error message experiences in TypeScript are not good for these derived types, so we instead also manually maintain a copy of the types.  We then attempt to verify that the manually …
> Update ecs types

- CHANGELOG.md
- nodejs/awsx/ecs/taskDefinition.ts
- nodejs/awsx/package.json
I debated between taking a breaking change (as I'm doing here) vs. specifying the actual ARN string "arn:aws:iam::aws:policy/AmazonECS_FullAccess". Given this package is still in preview, the next release from a semver perspective is still a major release, so I think that's the right thing to do here versus trying to maintain backward compatibility.
> Swap AmazonEC2ContainerServiceFullAccess for AmazonECS_FullAccess

- CHANGELOG.md
- nodejs/awsx/ecs/taskDefinition.ts
- nodejs/awsx/package.json
- Update to `@pulumi/aws` 3.25.1 so that callback functions without specified policies create a copy of the deprecated policy.
- [Breaking] Update the default task role in `ecs.TaskDefinition` to use the more scoped down `LambdaFullAccess` policy (the new one that AWS recommends).
> Update for Lambda full access deprecation

- CHANGELOG.md
- nodejs/awsx/apigateway/api.ts
> Ensuring apigateway.RestApiArgs are up to date with the pulumi-aws library

- CHANGELOG.md
- nodejs/awsx/aws_test.go
- nodejs/awsx/ecs/capacityProviderService.ts
- nodejs/awsx/ecs/ec2Service.ts
- nodejs/awsx/ecs/fargateService.ts
- nodejs/awsx/ecs/index.ts
- nodejs/awsx/ecs/service.ts
- nodejs/examples/ecs/capacity-provider-service-ec2-custom-strategy/.gitignore
- nodejs/examples/ecs/capacity-provider-service-ec2-custom-strategy/Pulumi.yaml
- nodejs/examples/ecs/capacity-provider-service-ec2-custom-strategy/index.ts
- nodejs/examples/ecs/capacity-provider-service-ec2-custom-strategy/package.json
- nodejs/examples/ecs/capacity-provider-service-ec2-custom-strategy/tsconfig.json
- nodejs/examples/ecs/capacity-provider-service-with-cluster-default-strategies/.gitignore
- nodejs/examples/ecs/capacity-provider-service-with-cluster-default-strategies/Pulumi.yaml
- nodejs/examples/ecs/capacity-provider-service-with-cluster-default-strategies/index.ts
- nodejs/examples/ecs/capacity-provider-service-with-cluster-default-strategies/package.json
- nodejs/examples/ecs/capacity-provider-service-with-cluster-default-strategies/tsconfig.json
From #599 I  modified @leezen  class name a bit and called it `CapacityProviderService` and you pass the taskDefinition that would either be a FargateTaskDefinition or EC2TaskDefinition. With that, the user would know exactly wich path he is going. Now underlying capacity provider can be anything and we can still leverage the cluster default capacity provider strategy without any extra flag.
Note that I've implemented a different idea before (#643) but as @leezen said, It makes more sense to have a different class for this. Also, from now on you can't define `capacityProviderStrategies` in `FargateService` nor `EC2Service`. In that way, this PR fixes #599.
> Create CapacityProviderService to make it possible to use capacity provider strategies

- nodejs/awsx/ecs/capacityProviderService.ts
- nodejs/awsx/tsconfig.json
@stack72 Any chance you know what's going on here? Even locally, with `2016-2018` the linter is fine. With `2016-2021` or even just plain `2021` the linter complains.
> Fix the copyright header for linting

- CHANGELOG.md
- nodejs/awsx/lb/listener.ts
- nodejs/awsx/lb/network.ts
- nodejs/awsx/lb/targetGroup.ts
> Add support for GENEVE, UDP and TCP_UDP in awsx.lb.TargetGroup Protocols

- CHANGELOG.md
- nodejs/awsx/s3/metrics.ts
To use the S3 `numberOfObjects` metric, I needed the `storageType: "AllStorageTypes"`.  When I referenced the AWS documentation, I realized many other storageTypes were missing: https://docs.aws.amazon.com/AmazonS3/latest/userguide/metrics-dimensions.html#s3-cloudwatch-dimensions
This PR adds the most up-to-date list of storageTypes for S3 metrics.
I'm not sure what to do about lines `149-174` in `nodejs/awsx/s3/metrics.ts`, which repeats storage types, but I wasn't sure if that that was intended to be a limited subset of options.
> Add additional StorageTypes to awsx.s3.metrics

- CHANGELOG.md
- nodejs/awsx/billing/index.ts
- nodejs/awsx/billing/metrics.ts
- nodejs/awsx/index.ts
Usage:
```
const estimatedCharges = awsx.billing.metrics.estimatedCharges({
currency: "USD",
period: 21600,
statistic: "Maximum",
});
estimatedCharges.createAlarm("billing.estimatedCharges", {
alarmActions: [topicAlerts],
evaluationPeriods: 1,
okActions: [topicAlerts],
threshold: 1000,
treatMissingData: "breaching",
});
const estimatedChargesEc2 = awsx.billing.metrics.estimatedCharges({
currency: "USD",
period: 21600,
serviceName: "AmazonEC2",
statistic: "Maximum",
});
estimatedChargesEc2.createAlarm("billing.AmazonEC2.estimatedCharges", {
alarmActions: [topicAlerts],
evaluationPeriods: 1,
okActions: [topicAlerts],
threshold: 100,
treatMissingData: "breaching",
});
```
Adds https://github.com/pulumi/pulumi-awsx/issues/658
> Add support for Billing CloudWatch metrics and alarms

- CHANGELOG.md
- nodejs/awsx/ecs/capacityProviderService.ts
- nodejs/awsx/ecs/ec2Service.ts
- nodejs/awsx/ecs/fargateService.ts
- nodejs/awsx/ecs/service.ts
- nodejs/awsx/package.json
> Add support for ECS Service Circuit Breaker and Execute Command

- CHANGELOG.md
- nodejs/awsx/autoscaling/launchConfiguration.ts
- nodejs/examples/alb/ec2Instance/index.ts
- nodejs/examples/metrics/index.ts
`aws.getAmi()` is being deprecated https://www.pulumi.com/docs/reference/pkg/aws/getami/﻿
Fixes #680
> Use aws.ec2.getAmi() instead of aws.getAmi()

- nodejs/awsx/aws_test.go
It's been a couple weeks since https://github.com/pulumi/pulumi-awsx/issues/686 and given we currently get no value from the tests, let's skip these ones.
> Skip tests that rely on VpcLink resource

- nodejs/awsx/ec2/subnet.ts
Increase the timeouts. While we've only been seeing issues with deletes, I'm preemptively doing this for create as well since we'd seen that happen in the past with route table associations where we later saw the need on the create side.
I'm marking as `no-changelog-required` as there's no real user-facing change here in my opinion, but open to the opposite opinion that the timeout change is a behavior change that should be called out.
> Increase create/delete timeouts for Route resource

- CHANGELOG.md
- nodejs/awsx/ecs/service.ts
> Support multiple load balancing listeners per container

- nodejs/awsx/apigateway/api.ts
- nodejs/awsx/apigateway/index.ts
- nodejs/awsx/package.json
This pulls out the RestAPI resource creation into a function that can be reused in other packages to construct the desired child resource directly parented to another resource.  This is expected to be used in exposing this as a multi-language component.
> Refactor API implementation

- CHANGELOG.md
- nodejs/awsx/autoscaling/launchConfiguration.ts
Apparently, Amazon has changed the default AMI snapshot and it doesn't fit our default 8 GB anymore. Extend root block device size to fit the new image in test capacity-provider-service-ec2-custom-strategy test.
Fix https://github.com/pulumi/pulumi-awsx/issues/717
> Extend root block device size to fit the new image

- CHANGELOG.md
- nodejs/awsx/ec2/README.md
- nodejs/awsx/ec2/vpc.ts
- nodejs/examples/vpc/index.ts
- nodejs/examples/vpc/package.json
Fixing: https://github.com/pulumi/pulumi-awsx/issues/493
Fixed the [review comments](https://github.com/pulumi/pulumi-awsx/pull/494) and made sure to base of v2. 
Took the liberty of adding deprecation warning to `numberOfAvailabilityZones` and introducing `requestedAvailabilityZone?: number | "all" | [string, ...string[]];`
That being said, I am not sure it's a great idea to rely on fresh calls to `getAvailabilityZones()`, maybe I'm wrong here, but couldn't there be a potential issue of getting different zones back, thus mutating an existing VPC? 
Assuming it does what I suspect, I'd think it's better to allow the user to decide if throwing an error is better than mutating an existing VPC when AWS returns different zones than what you're expecting. 
My take is, remove `"all"` & `number` …
> Allow using specific zones when creating a VPC.

- schemagen/go.mod
- schemagen/go.sum
- sdk/go.mod
- sdk/go.sum
- sdk/go/awsx/awsx/pulumiTypes.go
- sdk/go/awsx/cloudtrail/trail.go
- sdk/go/awsx/ec2/defaultVpc.go
- sdk/go/awsx/ec2/pulumiEnums.go
- sdk/go/awsx/ec2/pulumiTypes.go
- sdk/go/awsx/ec2/vpc.go
- sdk/go/awsx/ecr/image.go
- sdk/go/awsx/ecr/pulumiTypes.go
- sdk/go/awsx/ecr/repository.go
- sdk/go/awsx/ecs/ec2service.go
- sdk/go/awsx/ecs/ec2taskDefinition.go
- sdk/go/awsx/ecs/fargateService.go
- sdk/go/awsx/ecs/fargateTaskDefinition.go
- sdk/go/awsx/ecs/pulumiTypes.go
- sdk/go/awsx/lb/applicationLoadBalancer.go
- sdk/go/awsx/lb/networkLoadBalancer.go
- sdk/go/awsx/lb/pulumiTypes.go
- sdk/go/awsx/lb/targetGroupAttachment.go
Updates the Go SDK codegen and dependencies to support:
- https://github.com/pulumi/pulumi/issues/9506
- https://github.com/pulumi/pulumi/issues/9507
This improves the Go SDK so that the following example can run without ApplyT:
```go
package main
import (
aws_ecs "github.com/pulumi/pulumi-aws/sdk/v5/go/aws/ecs"
"github.com/pulumi/pulumi-awsx/sdk/go/awsx/ecs"
"github.com/pulumi/pulumi-awsx/sdk/go/awsx/lb"
"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)
func main() {
pulumi.Run(func(ctx *pulumi.Context) error {
cluster, err := aws_ecs.NewCluster(ctx, "cluster", nil)
if err != nil {
return err
}
lb, err := lb.NewApplicationLoadBalancer(ctx, "lb", nil)
if err != nil {
return err
}
_, err = ecs.NewFargateService(ctx, "nginx", &ecs.FargateServiceArgs{
Cluster: cluster.Arn,
TaskDefinitionArgs: …
```
> Support chaining and shallow plain types in Go SDK

- examples/examples_nodejs_test.go
Change reason for skipping TestDefaultVpc to point to relevant issue.
The relevant issue is https://github.com/pulumi/pulumi-awsx/issues/788 and not https://github.com/pulumi/pulumi-awsx/issues/784
Note: I didn't add a changelog entry as I didn't think it was necessary as this change doesn't impact crosswalk.
> Change reason for skipping TestDefaultVpc to point to relevant issue

- .github/workflows/master.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- .github/workflows/run-acceptance-tests.yml
- Makefile
- awsx/scripts/generate-provider-types.ts
- examples/examples_nodejs_test.go
For some reason, if the binary already exists in the gobin then after copying the new executable it fails with a message such as
```
[1]    9392 killed     ./pulumi-resource-awsx
```
To work around this, we'll just delete before copying, though not entirely sure why this works.
> Fix local provider install

- CHANGELOG.md
- awsx-classic/apigateway/api.ts
- awsx-classic/apigateway/lambdaAuthorizer.ts
- awsx-classic/ec2/vpcTopology.ts
- awsx-classic/ecs/taskDefinition.ts
- awsx-classic/package.json
- awsx-classic/tsconfig.json
- awsx/schema.json
- schemagen/pkg/gen/schema.go
- sdk/nodejs/classic/apigateway/api.ts
- sdk/nodejs/classic/apigateway/lambdaAuthorizer.ts
- sdk/nodejs/classic/ec2/vpcTopology.ts
- sdk/nodejs/classic/ecs/taskDefinition.ts
- sdk/nodejs/package.json
Moves two dependencies out of devDeps into primary deps, and removes internal annotations that caused type errors.
Fixes #853
> fix: add necessary dependencies for type checking to succeed

- awsx-classic/apigateway/api.ts
- awsx-classic/package.json
- awsx/package.json
- awsx/schema.json
- awsx/yarn.lock
- schemagen/pkg/gen/schema.go
- sdk/nodejs/classic/apigateway/api.ts
- sdk/nodejs/package.json
- Use pulumi dev release until 3.34 is available - this resolves the ERR_INSPECTOR_NOT_AVAILABLE warnings
- Fix errors from typescript 4.7 release - revert pinning of typescript to 4.6.
> Fix build warnings

- .github/workflows/old-release.yml
- .github/workflows/release.yml
- Makefile.old
We need to push a patch of a regression of the v0.40.x series but
our currently release machinery is specifically set up for the
new way of working
> [internal] Add a release script that will work for the v0.40.x series

- awsx/ec2/vpc.test.ts
- awsx/ec2/vpc.ts
> Do not throw an exception when NAT gateway strategy is None.

- awsx-classic/apigateway/api.ts
- sdk/nodejs/classic/apigateway/api.ts
- The SDK typescript version is not locked, so an upgrade caused this to start failing.
> Fix type resolution bug

- .github/workflows/cron.yml
Noticed there were duplicate "master" workflows in the Actions tab.
> Fix cron workflow name.

- CHANGELOG.md
- awsx/ecr/image.ts
- awsx/ecs/ec2Service.ts
- awsx/ecs/fargateService.ts
The docs say this should default to `false`, and the implementation appears to be trying to implement that, but it applies `!` to an `Output` value, which will always be `false`, even if the `Output` internally evaluates to `false`.  Instead, apply the `!` inside an apply.
Also remove accidentally added debug logging.
Fixes #902.
TODO: Ideally we should add tests that validate the service is available immediately after the `pulumi up` completes, without the need to retry 503s.
> Fix continueBeforeSteadyState

- .github/workflows/cron.yml
- .github/workflows/master.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- .github/workflows/run-acceptance-tests.yml
- awsx-classic/ec2/vpcTopology.ts
- sdk/nodejs/classic/ec2/vpcTopology.ts
Causes the declaration files to have errors due to the type being excluded by the `"stripInternal": true,` option.
Fixes #924
It appears everything used to be internal, but was [recentlly made public](https://github.com/pulumi/pulumi-awsx/commit/a76d499d1e948dd9850e9c25c4fc5e5422ede296). Give this type is refered to by public types, this must also be exposed.
> Remove internal attribute

- awsx/ec2/vpc.ts
All resources should get the tags assigned to them.
In addition, I've added the subnet type to the route tables so we can differentiate them
Fixes #922
> propagate tags to all resources

- CHANGELOG.md
- awsx/schema.json
- schemagen/pkg/gen/schema.go
- sdk/python/setup.py
v3.47.2 of the `pulumi` package has been released.
Fixes #929
> Bump min required version of `pulumi` PyPi package to 3.47.2

- .github/workflows/cron.yml
- .github/workflows/master.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- .github/workflows/run-acceptance-tests.yml
We're installing 3.1 on an image which already has 6.0. This has no effect as dotnet will automatically choose the newest version.
This was found because were getting an error on the acceptance tests where we used the install action but failed to specify the matrix.dotnetversion which meant the action automatically installed the latest version (7.0) which caused build errors.
> Remove explicit dotnet install

- awsx/ec2/vpc.ts
- examples/vpc/nodejs/vpc-subnets-with-tags/Pulumi.yaml
- examples/vpc/nodejs/vpc-subnets-with-tags/index.ts
- examples/vpc/nodejs/vpc-subnets-with-tags/package.json
- examples/vpc/nodejs/vpc-subnets-with-tags/tsconfig.json
Tags in the SubnetSpec for a VPC were not being applied to subnets.
This PR adds the SubnetSpec tags to the VPC subnets _after_ the top-level (VPC-spec) tags, so that matching SubnetSpec tags will take precedence.
Fixes #922
> Create tags on vpc subnets from tags in subnet spec

- awsx/ec2/vpc.ts
Fixes #967, #985
As described in the above issues it's currently impossible to actually set the name of a VPC, for two different reasons.
This PR fixes both issues. I don't _think_ it will cause a regression that anybody notices, because right now setting a name causes creation of the VPC to fail.
---
A "nice to have" would be constructing the name tag of each subnet based on the name tag of the over all VPC, but that's a bigger change/feature so I'd rather treat this PR as simply a bug fix.
> Re-order tag priority in ec2.Vpc

- awsx/ec2/subnetDistributor.ts
- awsx/ec2/vpc.ts
This reverts commit 4a0b97b90336bae76b7a0c8d210cf271d2c8dc72 from #1014 which [fails the "cron" CI tests](https://github.com/pulumi/pulumi-awsx/actions/runs/5472516109). It needs more work because when we don't have an IPAM Pool Id, we still need to use a default CIDR block (the previous `cidrBlock = args.cidrBlock ?? "10.0.0.0/16"` line).
Resolves #1039
> Revert "Adopt IPAM functionality (#1014)"

- .github/workflows/release.yml
~~Because this repo doesn't contain a `schema.json`, these workflow-dispatch calls [always fail](https://github.com/pulumi/registry/actions/runs/5749835730/job/15585412356) (and generate [P1 issues](https://github.com/pulumi/registry/issues/2920) for the docs team), so this change just removes them.~~
Adds a flag to pass the path to `schema.json` when dispatching actions to the Registry in the `release` workflow. 
Fixes https://github.com/pulumi/registry/issues/2920.
> Pass `--schema-path` with docs-build requests to pulumi/registry

- awsx-classic/ec2/vpc.ts
- sdk/nodejs/classic/ec2/vpc.ts
Fixes #925 for the classic module.
> Stop using deprecated aws.ec2.getSubnetIds in classic

- awsx-classic/ec2/vpcTopology.ts
- awsx-classic/ecs/taskDefinition.ts
- awsx-classic/package.json
- awsx-classic/tests/package.json
- sdk/nodejs/classic/ec2/vpcTopology.ts
- sdk/nodejs/classic/ecs/taskDefinition.ts
- Fix classic compilation issues due to diverging aws-sdk and aws-sdk/client-ecs
- Resurrect the istanbul_tests suite for awsx-classic
> Fix build issues caused by recent aws-sdk release, fix classic tests

- awsx/ecr/image.ts
- examples/examples_nodejs_test.go
- examples/ts-ecr-dockerfile/Pulumi.yaml
- examples/ts-ecr-dockerfile/README.md
- examples/ts-ecr-dockerfile/app/content/index.html
- examples/ts-ecr-dockerfile/docker/Dockerfile
- examples/ts-ecr-dockerfile/index.ts
- examples/ts-ecr-dockerfile/package.json
- examples/ts-ecr-dockerfile/tsconfig.json
Apparently, we don't pass the `dockerfile` option to the ECR image. This PR is a one-line change to actually use it. I added a new E2E test to validate, let me know if you see a better testing opportunity.
Fix https://github.com/pulumi/pulumi-awsx/issues/1109
> Pass the dockerfile option to ECR image

- awsx/ec2/subnetDistributor.test.ts
- awsx/ec2/subnetDistributor.ts
- awsx/package.json
- awsx/yarn.lock
Using hard coded /19, /20 and /24 masks doesn't work when the VPC range is too small. This result in negative "new bits" and therefore subnets which are bigger than the available space. 
We need to maintain backward compatibility, so anyone generating valid subnets right now will continue with the same results. Therefore, we use an alternative, calculated mask if the minimal size block (largest mask number) is larger than the hard-coded value. 
Add a test to validate all combinations (144 possibilities) result in subnets which are not larger than the VPC's original CIDR block. This is a pretty crude test, but was used to find the deficient code.
- Related to #982
> Fix hard coded subnet masks

- awsx/ec2/knownWorkingSubnets.ts
- awsx/ec2/subnetDistributor.test.ts
- awsx/ec2/subnetDistributor.ts
- awsx/package.json
- awsx/schema.json
- awsx/yarn.lock
- schemagen/pkg/gen/ec2.go
- sdk/dotnet/Ec2/Vpc.cs
- sdk/go/awsx/ec2/vpc.go
- sdk/java/src/main/java/com/pulumi/awsx/ec2/VpcArgs.java
- sdk/nodejs/ec2/vpc.ts
- sdk/python/pulumi_awsx/ec2/vpc.py
Fix a bug in the subnet distributor which causes CIDR blocks to be generated where the blocks overlap with one another - causing an undeployable configuration.
Generate 100 test cases of known working subnet configurations to ensure we don't change the ouput for existing deployments. We **only** want to change the behaviour for cases which current cause overlaps.
Combine the old broken allocation method with an additional check for overlapping the previous block. If there's an overlap, then use the new strategy. This avoids affecting anyone who's already got a working deployment. Using only the new method sometimes generates more compact arrangements hence causing breaking changes.
- This is stacked on top of https://github.com/pulumi/pulumi-awsx/pull/1130
- Fixes #982
> Fix subnet overlapping

- awsx/ecr/image.ts
By having `image` hard-coded, pulumi can never succeed with multiple images in the same stack because the name conflicts.
> Ensure the resource name uses the uniquely generated name to avoid conflicts

- awsx/ecr/image.ts
This PR was merged prematurely. As is, it would cause existing image resources to be replaced due to the name change.
This reverts commit 43bb1447a20e804f6f7015df00ea8e26d8625aa9.
> Revert "Ensure the resource name uses the uniquely generated name to avoid conflicts (#1126)"

- awsx/ecr/image.ts
This reverts commit af69664ec8c6a46edfdbd4cca079d3c652381015.
Revive PR #1126 by @JoeStead since it was actually sound. The hard-coded image name was only introduced in v2, so backwards compatibility is not a concern.
> Revert "Revert "Ensure the resource name uses the uniquely generated name to avoid conflicts (#1126)" (#1141)"

- awsx/schema-types.ts
- schema.json
- schemagen/pkg/gen/ecr.go
- sdk/dotnet/Ecr/Image.cs
- sdk/go/awsx/ecr/image.go
- sdk/go/awsx/ecr/pulumiTypes.go
- sdk/java/src/main/java/com/pulumi/awsx/ecr/ImageArgs.java
- sdk/nodejs/ecr/image.ts
- sdk/python/pulumi_awsx/ecr/image.py
This would be a breaking change, but this argument is already not
working anymore since it was removed from the underlying Docker provider,
see pulumi/pulumi-docker#424.
Part of #1148
> Remove awsx.Ecr.ImageArgs.extraOptions

- awsx/ecs/container.test.ts
- awsx/ecs/containers.ts
> Fix getMappingInputs removing valid arguments

- .github/workflows/cron.yml
- .github/workflows/master.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
Our `publish_sdk` workflow is currently [broken](https://github.com/pulumi/pulumi-awsx/actions/runs/7400736741) because pypi no longer accepts passwords.
Unclear why we weren't alerted for this workflow failure.
Refs https://github.com/pulumi/ci-mgmt/issues/751
Refs https://github.com/pulumi/ci-mgmt/pull/767
> Fix pypi credentials

- scripts/publish_packages.sh
The publish script was using a hard-coded username instead of the `PYPI_USERNAME` environment variable.
> Fix pypi credentials again

- awsx/ec2/knownWorkingSubnets.ts
- awsx/ec2/subnetDistributorLegacy.test.ts
- awsx/ec2/subnetDistributorLegacy.ts
- awsx/ec2/subnetDistributorNew.test.ts
Fixes #1204 
- Assuming all subnets are the same size is overly cautious and breaks some existing setups.
- Maintain the new special case for single subnet layouts to use the whole of small VPCs.
- This will now fail and require manual layout for smaller VPCs with either:
- More than 1 private subnets
- More than 2 public subnets
- More than 1 public subnets and more than 4 isolated subnets
> Fix VPC legacy default subnet distribution

- awsx/ecr/image.ts
- awsx/schema-types.ts
- devbox.lock
- schema.json
- schemagen/pkg/gen/ecr.go
- sdk/dotnet/Ecr/Image.cs
- sdk/go/awsx/ecr/image.go
- sdk/go/awsx/ecr/pulumiTypes.go
- sdk/java/src/main/java/com/pulumi/awsx/ecr/ImageArgs.java
- sdk/nodejs/ecr/image.ts
- sdk/python/pulumi_awsx/ecr/image.py
Duplicate of https://github.com/pulumi/pulumi-awsx/pull/1225
Forked from a personal account to enable "Allow edits by maintainers"
> This PR aims to solve issue https://github.com/pulumi/pulumi-awsx/issues/1224
Adds the imageTag parameter to the Image resource.
The parameter is optional, if omitted the existing logic is used.
> Add imageTag parameter to ecr image resource v2

- awsx/ecr/image.ts
- awsx/schema-types.ts
- schema.json
- schemagen/pkg/gen/ecr.go
- sdk/dotnet/Ecr/Image.cs
- sdk/go/awsx/ecr/image.go
- sdk/java/src/main/java/com/pulumi/awsx/ecr/ImageArgs.java
- sdk/nodejs/ecr/image.ts
- sdk/python/pulumi_awsx/ecr/image.py
`aws.ecr.Image` makes assumptions about the ID of an ECR reigstry.  It assumes the registry ID [can be extracted from the repository URL](https://github.com/pulumi/pulumi-awsx/blob/9f18b3866d2a16a59d662384a0c745e2e5603463/awsx/ecr/image.ts#L36).
This assumption seems to hold true for the real AWS APIs, but I don't think AWS actually specify this behaviour in any of their documentation.
The assumption **does not** hold true for localstack, leading to [this issue](https://github.com/localstack/localstack/issues/7186).
This PR allows the caller to (optionally) specify a `registryId`, avoiding the inference logic mentioned above.
I edited `awsx/schema-types.ts` by hand.  I couldn't figure out how to generate that file.
> Support ECR images on localstack

- awsx/ecr/image.ts
- awsx/schema-types.ts
Fixes https://github.com/pulumi/pulumi-awsx/issues/1244
I've ran `make build provider` locally and it had the same diff as the CI.
> Fix order of code generation in schema-types.ts

- awsx/ecs/container.test.ts
- awsx/ecs/containers.ts
- awsx/ecs/fargateTaskDefinition.ts
The [container
definition](https://www.pulumi.com/registry/packages/aws/api-docs/ecs/taskdefinition/#containerdefinitions_nodejs) property of a Task Definition is a JSON string. We do not provide types for the container definition which means it is possible to include things in that JSON string that shouldn't be there. In the case of this bug, we are including an additional `targetGroup` object in the container definition string.
To fix this, I am removing the `targetGroup` field. 
fix #1248
> fix: targetGroup errors appear in containerDefinition diff

- awsx/ecr/image.ts
- awsx/schema-types.ts
- schema.json
- schemagen/pkg/gen/ecr.go
- sdk/dotnet/Ecr/Image.cs
- sdk/go/awsx/ecr/image.go
- sdk/go/awsx/ecr/pulumiTypes.go
- sdk/java/src/main/java/com/pulumi/awsx/ecr/ImageArgs.java
- sdk/nodejs/ecr/image.ts
- sdk/python/pulumi_awsx/ecr/image.py
Fixes #1171
This allows the user to manually choose the name of the underlying Pulumi Docker image resource
When not defined it will fall back to the original behavior (use the image tag as the name of the underlying resource)
> Add imageName param to ECR image args

- examples/examples_nodejs_test.go
This test has been creating P1s and blocking PR verification; we are waiting on a feature fix from platform to enable increasing custom timeout. IN the meanwhile skipping it is reasonable.
> Skip flaky TestLbWithSubnets

- DEVELOPMENT.md
- Makefile
- examples/examples_dotnet_test.go
The DotNet tests require the path to the directory containing the awsx nuget package to be set using `PULUMI_LOCAL_NUGET`. This adds functionality for automatically setting this env variable with the path to the dotnet sdk
Also added a convenience make target to install all SDKs
> Change DotNet tests to auto configure PULUMI_LOCAL_NUGET

- .github/workflows/cron.yml
- .github/workflows/master.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- .github/workflows/run-acceptance-tests.yml
Fixes recent failure of AWS Classic lint on master. Latest dependencies of pulumi/pulumi no longer work with 16.
https://github.com/pulumi/pulumi-awsx/issues/1268
> Standardize CI on Node 18

- awsx/ec2/subnetDistributorNew.test.ts
- awsx/ec2/subnetDistributorNew.ts
Previously when using the explicit subnet distribution strategy (i.e. when specifying specific subnet CIDRs) the tags didn't get propagated to the subnet. This fixes that.
Fixes https://github.com/pulumi/pulumi-awsx/issues/1287
> Propagate subnet tags for explicit strategy

- awsx/ecs/fargateMemoryAndCpu.test.ts
- awsx/ecs/fargateMemoryAndCpu.ts
In the prior implementation, if an ECS task's requested resources surpassed the Fargate limits, the system defaulted to the maximum resources permitted by Fargate.
This led to obscure AWS API errors indicating that the containers were requesting more resources than the task could provide.
Fixes #1220
> Ensure requested ECS container resources are within Fargate limits

- README.md
- sdk/python/README.md
Documents how AWS provider version is selected and gives an example of overriding it.
Fixes https://github.com/pulumi/pulumi-awsx/issues/1191
> Document AWS version resolution

- .github/workflows/weekly-pulumi-update.yml
- scripts/bump-pulumi-deps.sh
- scripts/get-latest-pulumi-version.sh
This sets up a cron job to bump pulumi/pulumi versions every week. The cron job updates the dependencies, rebuilds the provider and then opens a PR. The PR is set to auto merge.
Closes #1264
> Automate weekly pulumi/pulumi upgrade

- .github/workflows/cron.yml
- .github/workflows/master.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- .github/workflows/run-acceptance-tests.yml
- .github/workflows/version.yml
- .github/workflows/weekly-pulumi-update.yml
- Makefile
- schema.json
- schemagen/pkg/gen/schema.go
- sdk/dotnet/Pulumi.Awsx.csproj
- sdk/dotnet/pulumi-plugin.json
- sdk/go/awsx/internal/pulumiUtilities.go
- sdk/go/awsx/pulumi-plugin.json
- sdk/nodejs/package.json
- sdk/python/pulumi_awsx/pulumi-plugin.json
- sdk/python/pyproject.toml
Part of https://github.com/pulumi/ci-mgmt/issues/915
Bring workflows in line with the approach used in other providers.
1. Use action for checking for unexpected changes - and allow files with the version embedded to change once we've enabled `respectSchemaVersion`.
2. Fix how we calculate the version we're building. Stop relying on the local git checkout to contain all tags. Use a placeholder locally and override the placeholder in CI with the version calculated from our action.
- Remove fetching all tags.
3. (Pending) enable `respectSchemaVersion`.
> Embed SDK version

- .github/workflows/master.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
There were some leftovers of the `pulumictl` based version lookup that started failing master builds and releases after the unshallow clone was removed (because it couldn't resolve the correct version without having access to all tags).
This change switches them over to use the output of the provider-version-action.
Fixes #1305
> Fix lookup of provider version to use versioning action

- .github/workflows/command-dispatch.yml
- .github/workflows/weekly-pulumi-update.yml
This change makes it easier to debug the weekly pulumi update by allowing it to be dispatched
via the command run-pulumi-update.
The auto merge will be disabled for the automated upgrades. Otherwise those commits will get merged into the PR branch
> Add repository dispatch command for testing weekly pulumi upgrade in PRs

- .github/workflows/weekly-pulumi-update.yml
Previously the weekly pulumi upgrade couldn't auto-merge because it used the built-in action access token for creating the PR. That default GH action user doesn't have the necessary access rights (i.e. is not a member of pulumi) to run acceptance tests.
This change makes the gh cli use the pulumi bot token.
> Modify weekly pulumi upgrade action to run acceptance tests in PR

- .github/workflows/release.yml
Follows the workflow defined in ci-mgmt (https://github.com/pulumi/ci-mgmt/blob/7c1f0521b8f04aff46732c6656659c85d60fd9c4/provider-ci/test-workflows/aws/.github/workflows/release.yml#L149-L186) as the basis for this change. This ensures that during the publishing step, we download the Go SDK artifact which contains the correctly embedded version. We then use the `pulumi/publish-go-sdk-action` action to commit/push the new files and cut a new sdk tag for this.
Fixes: #1322
> ci: fix go sdk publish to embed version

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
https://github.com/pulumi/pulumi-awsx/pull/1323 used v4 of the download artifact action, which is incompatible with uploads using v3 of the upload action. See [FAQ](https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md#which-versions-of-the-artifacts-packages-are-compatible) for compatibility matrix.
This resulted in the release step [failing](https://github.com/pulumi/pulumi-awsx/actions/runs/9620941727/job/26540766895#step:4:36) to download the uploaded artifact.
This PR also updates the pre-release workflow while we're at it.
Note: I've opted to use v3 of the download action to maintain consistency with the rest of our GHA workflows. We can update to v4 in the future.
> Use v3 of actions/download-artifact

- .github/workflows/weekly-pulumi-update.yml
- awsx/package.json
- awsx/yarn.lock
Adds automation for updating the pu/pu node dependency.
This also adds tools for deduplicating entries in the yarn.lock file. Those sometimes happen when upgrading dependencies... :( https://github.com/yarnpkg/yarn/issues/3967
> Automate updating pu/pu node dependency

- .github/workflows/weekly-pulumi-update.yml
This causes the version to flip-flop between builds.
We don't want a real version because we're pushing the code back as a PR.
> Don't set provider version during pulumi upgrades

- awsx/package.json
- awsx/yarn.lock
Also upgrades the dev dependencies `json-schema-to-typescript` and `typedoc` because they introduced dependency clashes that lead to the following build errors:
```
Error: node_modules/@types/glob/index.d.ts(29,42): error TS2694: Namespace '"/home/runner/work/pulumi-awsx/pulumi-awsx/awsx/node_modules/minimatch/dist/commonjs/index"' has no exported member 'IOptions'.
Error: node_modules/@types/glob/index.d.ts(75,30): error TS2724: '"/home/runner/work/pulumi-awsx/pulumi-awsx/awsx/node_modules/minimatch/dist/commonjs/index"' has no exported member named 'IMinimatch'. Did you mean 'Minimatch'?
Error: node_modules/@types/shelljs/node_modules/@types/glob/index.d.ts(29,42): error TS2694: Namespace '"/home/runner/work/pulumi-awsx/pulumi-awsx/awsx/node_modules/minimatch/dist/commonjs/index"' has …
```
> Upgrade @pulumi/pulumi version to v3.120.0

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
This updates the github workflows to auto generate release notes.
Additionally it bumps softprops/action-gh-release to v2.
> Auto generate Release Notes

- awsx/ec2/subnetDistributorNew.ts
- awsx/ec2/vpc.test.ts
- awsx/ec2/vpc.ts
The case analysis around picking which allocator to use is made more explicit and covered with a unit test.
> refactor: clarify how Vpc subnet allocators are chosen

- awsx/ec2/vpc.test.ts
- awsx/ec2/vpc.ts
The awsx.ec2.Vpc resource supports three subnet layout strategies: Auto, Exact, and Legacy. Consider the following program that does not specify the subnet specs:
new awsx.ec2.Vpc("vpc", {
subnetStrategy: "Auto",
});
Prior to this change, the code would implicitly use the Legacy strategy for this program even though Auto is requested. This is now fixed. The Auto strategy already supports allocating subnets without any explicit specs provided.
> Fix VPC support for Auto subnet layout strategy

- .github/workflows/cron.yml
- .github/workflows/master.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- .github/workflows/run-acceptance-tests.yml
This is to avoid the tests failing due to the token expiring.
Newly introduced IPAM-based tests are long running due to a known issue with slow deletions of aws.ec2.Vpc, see https://github.com/pulumi/pulumi-aws/issues/4346
> Increase AWS token timeout from 1h to 2h

- awsx/ec2/subnetDistributorLegacy.test.ts
- awsx/ec2/subnetDistributorLegacy.ts
- awsx/ec2/subnetDistributorNew.test.ts
- awsx/ec2/subnetDistributorNew.ts
- awsx/ec2/subnetSpecs.ts
- awsx/ec2/vpc.test.ts
- awsx/ec2/vpc.ts
- awsx/ec2/vpcConverters.ts
- awsx/schema-types.ts
- examples/examples_nodejs_test.go
- examples/vpc/nodejs/vpc-ipam-ipv4-auto-cidrblock-with-specs/.gitignore
- examples/vpc/nodejs/vpc-ipam-ipv4-auto-cidrblock-with-specs/Pulumi.yaml
- examples/vpc/nodejs/vpc-ipam-ipv4-auto-cidrblock-with-specs/index.ts
- examples/vpc/nodejs/vpc-ipam-ipv4-auto-cidrblock-with-specs/package.json
- examples/vpc/nodejs/vpc-ipam-ipv4-auto-cidrblock-with-specs/tsconfig.json
- examples/vpc/nodejs/vpc-ipam-ipv4-auto-cidrblock/.gitignore
- examples/vpc/nodejs/vpc-ipam-ipv4-auto-cidrblock/Pulumi.yaml
- examples/vpc/nodejs/vpc-ipam-ipv4-auto-cidrblock/index.ts
- examples/vpc/nodejs/vpc-ipam-ipv4-auto-cidrblock/package.json
- examples/vpc/nodejs/vpc-ipam-ipv4-auto-cidrblock/tsconfig.json
- schema.json
- schemagen/pkg/gen/ec2.go
Fixes issues with supporting the ipv4IpamPoolId parameter that ties a VPC to an IPAM pool. 
You should now be able to write the following to allows IPAM to allocate and manage a cidrBlock range. The VPC component now uses that dynamically allocated block to automatically configure subnets.
```typescript
new awsx.ec2.Vpc("myVpc", {
ipv4IpamPoolId: myVpcIpamPool.id,
ipv4NetmaskLength: 24,
subnetStrategy: "Auto",
});
```
It is also possible to constrain the allocated subnets with subnetSpecs, while still using IPAM to manage the overall cidrBlock range:
```typescript
new awsx.ec2.Vpc("myVpc", {
numberOfAvailabilityZones: 3,
subnetStrategy: "Auto",
ipv4IpamPoolId: myVpcIpamPool.id,
ipv4NetmaskLength: 22,
subnetSpecs: [
{
type: "Private",
name: "private",
cidrMask: 25,
},
{
type: "Public", …
```
> Permit aws.ec2.Vpc to use IPAM-allocated cidrBlock ranges

- awsx/ec2/vpc.ts
We can't use JSON.stringify on an output directly, we need to do that inside an apply. 
Fix https://github.com/pulumi/pulumi-awsx/issues/1372
> Rewrite a warning to avoid printing an output directly

- awsx/s3/bucket.ts
- awsx/utils.ts
- examples/examples_nodejs_test.go
The `getRegion` functions were incorrectly trying to extract the current region from the provider. This silently resolved to undefined in certain cases; e.g. when no `AWS_REGION` ENV variable was set.
In particular this caused ECS tasks to fail because they used `https://logs.undefined.amazonaws.com/` as the endpoint for cloudwatch.
Instead we should use the `getRegion` data source to correctly identify the current region.
Fixes #1112
Fixes #1279
> Fix getRegion functions

- schema.json
- schemagen/pkg/gen/schema.go
- sdk/nodejs/package.json
Looks like this was left behind after a migration to the V3 sdk.
fixes #1393
> chore: remove unused aws-sdk dependency

- awsx/ec2/vpc.ts
Another fix for https://github.com/pulumi/pulumi-awsx/issues/1372 while https://github.com/pulumi/pulumi-awsx/pull/1374 only partially succeeded.
The previous attempt was successful in resolving the top-level output but child outputs were still unresolved. I was a bit surprised that was the case... outputs are hard!
The new attempt relies on `pulumi.jsonStringify` which is made exactly for this purpose. This drops JSON formatting but hopefully that not too bad for a small JSON. Example of the result:
```
warning: The default subnetStrategy will change from "Legacy" to "Auto" in the next major version. Please specify the subnetStrategy explicitly. The current subnet layout can be specified via "Auto" as:
[{"cidrMask":20,"type":"Public"}]
```
> Rewrite a warning to avoid printing sub-properties as outputs

- scripts/upgrade-aws.sh
Fixes a small miss in the automation to keep the AWS dependency up-to-date.
> Rebuild awsx/schema-types.ts when upgrading AWS dependency

- .github/workflows/cron.yml
- .github/workflows/master.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- .github/workflows/run-acceptance-tests.yml
Hi, I'm opening this as [Github is deprecating the upload/download artifact actions](https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/) on 5th Dec.
We have a forked repo of pulumi-awsx and since we are bumping it for us it we thought it could be useful to open a PR here too.
Thanks all
> Bump deprecated download-upload artifact github actions

- examples/ecs/nodejs/index.ts
Pulumi was not recognizing that the underlying aws.ecs.Service should wait for the load balancer to be provisioned, causing a race that sporadically would flake up the test. This is now compensated by with a dependsOn option.
Fixes #1418
> testing: examples/ecs/nodejs add missing dependsOn

- awsx/ecr/image.test.ts
- awsx/ecr/image.ts
- examples/examples_nodejs_test.go
I noticed that https://github.com/pulumi/pulumi-awsx/pull/1278 introduced an (unreleased) breaking change in the `imageUri` output of `ecr.Image`.
Before upgrading to docker-build, the component returned URIs in the form of `ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/REPOSITORY_NAME@sha256:1234567890123456789012345678901234567890123456789012345678901234`.
After the update it returns them in the following form `ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/REPOSITORY_NAME:TAG_NAME@sha256:1234567890123456789012345678901234567890123456789012345678901234`. (NOTE: they include the tag name now)
While it seems like an innocent change, it breaks the integration with lambda functions. AWS Lambda expects an image URI without the TAG.
The change proposed in this PR adds post processing for the image ref in …
> Fix breaking change in `imageUri` output of `ecr.Image`

- .github/workflows/run-acceptance-tests.yml
With this change a PR can be stood up with changes to GitHub Actions workflows and the new version tested in that PR
> chore: enable testing CI changes

- .mk/renovate.mk
- renovate.json5
Suspect this will make https://github.com/pulumi/pulumi-awsx/pull/1479 start succeeding.
> chore: alias make renovate

- .mk/renovate.mk
When Renovate bot updates dependencies for the provider, we want to make sure that the new set of dependencies does not result in any duplication aka several versions of `@pulumi/pulumi` being included.
> chore: ensure Renovate deduplicates dependencies

- .mk/build.mk
- .mk/renovate.mk
This is an important check to include to fail early. If Renovate updates dependencies in a way that causes several copies of `@pulumi/pulumi` SDK to be included then the provider fails at runtime with an obscure error about invokes, as in https://github.com/pulumi/pulumi-awsx/pull/1479 - this will fail the build early instead.
> chore: ensure deduplicated dependencies

- examples/examples_nodejs_test.go
This test verifies that components like ECS services are created/updated in parallel. This took 1+ hours to run before fixing pulumi/pulumi#7629.
The test started to become more flaky recently (see https://github.com/pulumi/pulumi-awsx/issues/1488), this coincides with upgrading the GitHub runners to Ubuntu 24.04 and onboarding awsx to ci-mgmt. Those changes might've affected the test runtime and 15 minutes were probably a bit too aggressive.
Updated the timeout to 30min, which is still well below the 1 hour it took before.
Fixes https://github.com/pulumi/pulumi-awsx/issues/1488
> Increase timeout for `TestAccEcsParallel`

- awsx/ec2/vpc.test.ts
- awsx/ec2/vpc.ts
👋 I had some internal tagging policies fail when using the awsx.ec2.Vpc. I included the shared tags for the failing children (vpc endpoints) here. When testing it, I discovered that the vpc weren't being added to the component data, so I added that too. Along the way, I wrote some tests for other things that might have had the same problem, and I left them because they seem benign enough, and maybe even helpful.
I'm not familiar with this codebase, but it looks reasonable that `build_sdks` produced no output.
> [vpc/vpcEndpoints] use shared tags & expose endpoints

- awsx/ecs/containers.ts
My team has been running into issues with unnecessary container task definition updates for our services which causes lost time in waiting for these changes to be deployed.
The cause of this was having multiple containers where the containers would be getting mapped to the task definition in a non-predictable manor which lead to false positive changes.
This PR addresses that issue by ensuring we sort the containers for a task definition by their name in an effort to reduce these false positive changes from occurring.
> sort TaskDefinitionContainerDefinitionInputs by container name to reduce non-needed deploys

- scripts/upgrade-aws.sh
We started generating some new SDK types that aren't present in v7.0.0 of the AWS SDK. Update the script to have this SDK dependency track the version we're upgrading to.
Manually confirmed the script works again after this change.
Fixes https://github.com/pulumi/pulumi-awsx/issues/1669
> Fix upgrade-aws job
